"""Add associations table

Revision ID: 57f19c5e9bc6
Revises: 322dac5a514b
Create Date: 2026-06-02 13:00:51.333894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57f19c5e9bc6'
down_revision = '322dac5a514b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('associations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id_1', sa.Integer(), nullable=False),
    sa.Column('entity_id_2', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id_1'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id_2'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('associations')
    # ### end Alembic commands ###
